updated CI Pipeline to include Sonarcloud

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -1,10 +1,10 @@
-name: Build
+name: Build and Analyze
 
 on: [push]
 
 jobs:
   build:
-    name: Build and analyze
+    name: Build Project
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
@@ -15,20 +15,46 @@ jobs:
         with:
           java-version: 17
           distribution: 'zulu'
-      - name: Cache SonarCloud packages
-        uses: actions/cache@v3
-        with:
-          path: ~/.sonar/cache
-          key: ${{ runner.os }}-sonar
-          restore-keys: ${{ runner.os }}-sonar
       - name: Cache Maven packages
         uses: actions/cache@v3
         with:
           path: ~/.m2
           key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
           restore-keys: ${{ runner.os }}-m2
-      - name: Build and analyze
+      - name: Build
+        run: mvn -B clean verify
+
+  sonarqube-analysis:
+    name: SonarQube Analysis and Quality Gate Verification
+    runs-on: ubuntu-latest
+    needs: build
+    steps:
+      - uses: actions/checkout@v3
+        with:
+          fetch-depth: 0
+      - name: Cache SonarCloud packages
+        uses: actions/cache@v3
+        with:
+          path: ~/.sonar/cache
+          key: ${{ runner.os }}-sonar
+          restore-keys: ${{ runner.os }}-sonar
+      - name: SonarQube Scan
         env:
-          GITHUB_TOKEN: ${{ secrets.GITH_TOKEN }}
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
-        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=Claude-Lakoudji_paradise-game
+        run: mvn -B org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=Claude-Lakoudji_paradise-game -Dsonar.organization=your-sonarcloud-organization -Dsonar.host.url=https://sonarcloud.io
+      - name: Verify Quality Gate
+        run: |
+          # Wait for SonarQube to finish the analysis
+          sleep 10
+
+          # Query the SonarQube API to get the Quality Gate status
+          response=$(curl -s -u ${{ secrets.SONAR_TOKEN }}: "https://sonarcloud.io/api/qualitygates/project_status?projectKey=Claude-Lakoudji_paradise-game")
+          echo $response
+
+          # Check if the Quality Gate passed
+          if [[ $(echo $response | jq -r '.projectStatus.status') != "OK" ]]; then
+              echo "Quality Gate failed"
+              exit 1
+          fi
+        shell: bash
